    -   repo: https://github.com/jonathanlie94/reddit-clone-v1
        sha: ''  # Use the sha or tag you want to point at
        hooks:
        -   id: prettier
            args: [--single-quote --trailing-comma es5 --write] #list of args like '--single-quote', '--jsx-bracket-same-line', '--print-width 120', '--no-bracket-spacing'
            additional_dependencies: ['prettier@^1.5.2']
